# VORTA ULTRA Prometheus Configuration
# Enterprise-grade monitoring for AI Platform

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'vorta-ultra-monitor'
    environment: 'development'

rule_files:
  - 'rules/*.yml'

scrape_configs:
  # VORTA API Monitoring
  - job_name: 'vorta-api'
    static_configs:
      - targets: ['vorta-api:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    honor_labels: true
    params:
      format: ['prometheus']

  # PostgreSQL Monitoring
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # Redis Monitoring
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: '/metrics'

  # System Metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['localhost:9100']
    scrape_interval: 30s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana Monitoring
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'
    scrape_interval: 60s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
# Storage configuration
# Note: retention settings are now command line arguments, not config file settings
# Remote write configuration (optional for long-term storage)
# remote_write:
#   - url: "http://remote-storage:8086/api/v1/prom/write?db=vorta_metrics"
