groups:
  - name: vorta_alerts
    rules:
      - alert: VortaServiceDown
        expr: up{job="vorta-api"} == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: 'VORTA API service is down'
          description: 'VORTA API has been down for more than 30 seconds'

      - alert: HighCPUUsage
        expr: (100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100)) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High CPU usage detected'
          description: 'CPU usage is above 80% for more than 5 minutes'

      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: 'High memory usage detected'
          description: 'Memory usage is above 85% for more than 5 minutes'

      - alert: VortaInferenceLatencyHigh
        expr: histogram_quantile(0.95, rate(vorta_inference_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: 'High inference latency'
          description: '95th percentile inference latency is above 2 seconds'
