global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - 'rules/*.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vorta-api'
    static_configs:
      - targets: ['vorta-ultra-api:8000']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'vorta-inference-engine'
    static_configs:
      - targets: ['vorta-ultra-api:8001']
    metrics_path: '/health'
    scrape_interval: 10s

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
